attention:
  d_head: 160
  d_model: 160
  n_heads: 1
  n_layers: 6
ei:
  norm_strength: 0.2
  phase_corr_scale: 0.02
  use_EI: true
rails:
  use_B: true
  use_C: true
reentry:
  additive_nudge: 0.0
  mode: threshold_phase
resonator:
  atoms_per_filter: 3
  use_continuous_atoms: true
  use_retention_maps: true
timing:
  lambda_coverage: 0.005
  loss: softmin_cov
train:
  batch_size: 64
  dataset: text
  device: auto
  max_vram_gb: 12
  save_dir: runs/a_b_c_ei_mixlite_1500
  steps: 1500
  text_path: data/mix_lite_train.txt
